### ISSUE TITLE
baseUrl for console seems to be hardcoded in docker image

### ISSUE THREAD

**Issue by rshorser** [shipsaas/docking#24]
I'm trying to run docking using the latest docker image and while it runs fine, the console UI looks broken. Regardless of what I put in my env variables, it looks like the UI is referencing a baseUrl of     

`baseURL: "http://127.0.0.1:8888/api/v1"`

and thus returns an error when I try to login:

<img width="1566" alt="Screen Shot 2023-09-08 at 5 51 53 PM" src="https://github.com/shipsaas/docking/assets/779867/c01b97a2-46ed-4852-a379-bd4084d57d84">

My best guess is that this line [here](https://github.com/shipsaas/docking/blob/17686fd2234caf26cf9a111d1f8fc31dafc484fd/resources/js/console/factories/axios.js#L5) is getting set at build time and then ignoring whatever the VITE_APP_URL variable is set to. 

I can't tell very much how the static assets here are actually served, can the APIs just all be relative urls?

**Comment by sethsandaru** [comment]
Howdy @rshorser , thanks for the reporting.

And yes, you're right. `docking-dev` or `docking-dev-octane` should only be run in local/development mode. We'll always build the dev images using **the fixed env variables**.

It is recommended to build your own image ([Docker documentation](https://docking.shipsaas.tech/deployment/docker)) if you wish to have specific configurations (storage, DB type, URLs, etc.)

Lemme know if you still have any concern

**Comment by sethsandaru** [comment]
Please feel free to open this issue again if you have more questions, have a good one 😉
