### ISSUE TITLE
Errors during docker production image build

### ISSUE THREAD

**Issue by BraianPita** [shipsaas/docking#28]
I am trying Docking for the first time, and I went through the process of installing it through  building since I could not get pass the password section when trying the dev docker image.

I was getting the following error during docker build:

```
10.34 checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20220829
10.34 checking for PHP installed headers prefix... /usr/local/include/php
10.34 checking if debug is enabled... no
10.36 checking if zts is enabled... no
10.37 checking for gawk... no
10.37 checking for nawk... nawk
10.37 checking if nawk is broken... no
10.37 checking for PostgreSQL support for PDO... yes, shared
10.37 checking for pg_config... not found
10.37 configure: error: Cannot find libpq-fe.h. Please specify correct PostgreSQL installation path
------
prod.Dockerfile:26
--------------------
  24 |
  25 |     # Install PHP extensions
  26 | >>> RUN docker-php-ext-install pdo pdo_pgsql pdo_mysql mbstring exif pcntl bcmath gd
  27 |
  28 |     # Copy project files
--------------------
ERROR: failed to solve: process "/bin/sh -c docker-php-ext-install pdo pdo_pgsql pdo_mysql mbstring exif pcntl bcmath gd" did not complete successfully: exit code: 1

```
I used the following as reference: https://github.com/docker-library/php/issues/221

and added the following to the prod.Dockerfile
```
# Install Postgre PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql
```

And it was able to build the image successfully. But I am now getting the following:
<img width="960" alt="image" src="https://github.com/shipsaas/docking/assets/54162188/1a461dc7-434a-4635-bad0-7dec93336e27">

**Comment by sethsandaru** [comment]
thanks friend, lemme give it a look

**Comment by sethsandaru** [comment]
FYA I'm working on this https://github.com/shipsaas/docking/pull/29 and hopefully will merge it soon, so that you and everybody else won't suffer this kind of issue any more

**Comment by sethsandaru** [comment]
It has been released 💪 I'll close this one, thank you

https://github.com/shipsaas/docking/releases/tag/v1.4.2
